# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0002_auto_20170530_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emr.Status')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
