# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0003_statusgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusgroup',
            name='status_id',
        ),
        migrations.AddField(
            model_name='statusgroup',
            name='status_id',
            field=models.ManyToManyField(to='emr.Status'),
        ),
    ]
