# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0004_auto_20170530_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='original_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
