# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0006_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('resource_id', models.ManyToManyField(to='emr.Resource')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
