# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0007_appointmenttypegroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceUtilizationSlots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('resource_id', models.IntegerField()),
                ('monday', models.IntegerField()),
                ('tuesday', models.IntegerField()),
                ('wednesday', models.IntegerField()),
                ('thursday', models.IntegerField()),
                ('friday', models.IntegerField()),
            ],
        ),
    ]
