# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0008_resourceutilizationslots'),
        ('emr', '0007_resourcegroup'),
    ]

    operations = [
    ]
