# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0009_merge_20170531_1034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourceutilizationslots',
            options={'verbose_name_plural': 'Resource Utilization Slots'},
        ),
        migrations.RemoveField(
            model_name='resourceutilizationslots',
            name='name',
        ),
        migrations.AlterField(
            model_name='resourceutilizationslots',
            name='resource_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emr.Resource'),
        ),
    ]
